POST http://localhost:1111/api/v1/user/register
Content-Type: application/json

{
    "username":"tim",
    "password": "123456",
    "email":"t@abc.com"
}


###
POST http://localhost:1111/api/v1/user/login
Content-Type: application/json

{
    "username":"tim",
    "password": "123456",
    "email":"t@abc.com"

}

